base_app/urls.py
from django.contrib import admin
from django.urls import path, include

#media
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from users import views as users_views
from dashboard import views as dashboard_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    path('test', dashboard_views.test,name='test'),
    path('', dashboard_views.index,name='home'),
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('users/', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api-auth/', include('rest_framework.urls'))
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#urlpatterns += staticfiles_urlpatterns()

dashboard/urls.py
from django.urls import path
from . import views

app_name="dashboard"

urlpatterns = [
    path("",views.index,name="index"),
    path("index",views.index,name="index"),
]

users/urls.py
from django.urls import path
from . import views
from . import api
from rest_framework import routers

app_name = "users"

router = routers.DefaultRouter()
router.register('api/customers', api.customers_api)
# router.register('api/customers2',api.customers_api2)
# router.register('api/users_router',api.UsersViewSet)


urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("add", views.add, name="add"),
    path("signup", views.signup, name="signup"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path(r'^delete/(?P<row_id>\d+)/$', views.delete, name="delete"),
    path(r'^update_user/(?P<row_id>\d+)/$',
         views.update_user, name="update_user"),



    # api
    #to upload files
    path("upload-file/", api.FileUploadView.as_view(), name='upload-file'),
    #to get max id
    path("api/get_max_id/", api.get_max_id,name="get_max_id"),
    #to remove file
    path("api/remove_file/", api.remove_file,name="remove_file"),


    # path("api/users",api.get_users_api,name="get_users_api"),
    # path("api/users/<int:id>",api.get_user_api,name="get_user_api"),
    # path("api/users/add",api.save_user_api,name="save_user_api"),
    # path("api/get_users_class",api.get_users_class.as_view(),name="get_users_class"),
    # path("api/users_class2/<int:id>",api.users_class2.as_view(),name="users_class2"),
    path("api/customer_delete/<int:id>", api.customers_api.destroy, name="customer-delete"),



]
urlpatterns += router.urls

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render,redirect
from users import models
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required

@login_required(login_url="/users/login")
def index(request):
	return render(request,"dashboard.html",{'users':models.Users.objects.all().order_by('id')})

def test(request):
	return render(request,"test.html")

templates/about.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<h1>about</h1>
<img src="{% static '1.jpg' %}" alt="">
<form  method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="ok">
</form>




{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  
{% load static %}
{% include 'parts/head.html' %}

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'parts/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- navbar -->
                {% include 'parts/navbar.html' %}
                <!-- End of navbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                     <!-- Content here -->
                     {% block content %}

                     {% endblock %}
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">

            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>



    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <!-- <script src="vendor/chart.js/Chart.min.js"></script> -->

    <!-- Page level custom scripts -->
    <!-- <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script> -->

</body>


{% block scripts %}
{% endblock %}

</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}


<h1>dashboard</h1>

<div id="app">
  {{ users }}
 <br>
 [[ message ]]
  {% comment %} <app-count :message="123"></app-count>
  <app-count :message="message"></app-count> {% endcomment %}

</div>


{% endblock content %}





{% block scripts %}

<script>
  {% comment %} Vue.component('app-count',{
    delimiters: ['[[', ']]'],
    data: function () {
      return {
        name:'ahmad',
        count:0,
      }
    },
    template: '<p @click="count++">hi  [[ name ]]  the count =  [[count]] [[message]] .</p>',
    props:['message']
  }) {% endcomment %}

{% comment %} var vm = new Vue({
  el:'#app',
  delimiters: ['[[', ']]'],
  data:{
    message:'ok',
  },
}) {% endcomment %}



    // const { createApp } = Vue
  
    // createApp({
    //   data() {
    //     return {
    //       message: 'Hello Vue!'
    //     }
    //   }
    // }).mount('#app2')
</script>
  
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>index</h1>



<table class="table table-hover table-dark/ table-sm table-responsive">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">name</th>
        <th scope="col">email</th>
        <th scope="col">image</th>
      </tr>
    </thead>
    <tbody>

        {% for u in users %}
            <tr>
                <th scope="row">{{u.id}}</th>
                <td>{{u.name}}</td>
                <td>{{u.email}}</td>
                <td> <img src="{{ u.img.url }}" width="50" height="30" ></td>
            </tr>
        {% endfor %}




    </tbody>
  </table>



{% endblock content %}

templates/login.html
{% include 'parts/head.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"> 

<body class="d-flex h-100 text-center text-bg-dark">
    <main class="form-signin w-100 m-auto">
        <form class="site-form" method="post" action="{% url 'users:login' %}">
            <img class="mb-4" src="https://getbootstrap.com/docs/5.2/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            {% csrf_token %}

            {% comment %} to save the after login distenation {% endcomment %}
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}"
            {% endif %}

            {{form}}
            
            <input class="w-100 btn btn-lg btn-success" type="submit" value=" Login ">
        </form>
    </main>
    
</body>

templates/test.html
 {% extends 'base.html' %}

<!-- <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script> -->
{% block content %}
<div id="search-app">the message:{{query}}</div>

{% endblock %}

{% block scripts %}
<script>
    const SearchApp = {
        data() {
            return {
                query: '1',
                company_size: '',
                jobs: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            performSearch() {
                var data = {
                    'query': this.query,
                    'company_size': this.company_size
                }

                fetch('/jobs/api/search/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(data)
                })
                .then((response) => {
                    return response.json()
                })
                .then((result) => {
                    console.log(result.jobs)
                    this.jobs = result.jobs
                })
                .catch((error) => {
                    console.log('Error', error)
                })
            }
        }
    }

    Vue.createApp(SearchApp).mount('#search-app')
</script>
{% endblock %}