base_app/urls.py
from django.contrib import admin
from django.urls import path, include

#media
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from users import views as users_views
from dashboard import views as dashboard_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    path('test', dashboard_views.test,name='test'),
    path('', dashboard_views.index,name='home'),
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('users/', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api-auth/', include('rest_framework.urls'))
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views
from . import api
from rest_framework import routers

app_name = "users"

router = routers.DefaultRouter()
router.register('api/customers', api.customers_api)
# router.register('api/customers2',api.customers_api2)
# router.register('api/users_router',api.UsersViewSet)


urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("add", views.add, name="add"),
    path("signup", views.signup, name="signup"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path(r'^delete/(?P<row_id>\d+)/$', views.delete, name="delete"),
    path(r'^update_user/(?P<row_id>\d+)/$',
         views.update_user, name="update_user"),



    # api
    #to upload files
    path("upload-file/", api.FileUploadView.as_view(), name='upload-file'),
    #to get max id
    path("api/get_max_id/", api.get_max_id,name="get_max_id"),
    #to remove file
    path("api/remove_file/", api.remove_file,name="remove_file"),


    # path("api/users",api.get_users_api,name="get_users_api"),
    # path("api/users/<int:id>",api.get_user_api,name="get_user_api"),
    # path("api/users/add",api.save_user_api,name="save_user_api"),
    # path("api/get_users_class",api.get_users_class.as_view(),name="get_users_class"),
    # path("api/users_class2/<int:id>",api.users_class2.as_view(),name="users_class2"),
    path("api/customer_delete/<int:id>", api.customers_api.destroy, name="customer-delete"),



]
urlpatterns += router.urls

users/models.py
from django.db import models
#from django.contrib.auth.models import User


class Test_model(models.Model):
    a = models.CharField(max_length=1)
    b = models.CharField(max_length=50)

class Users(models.Model):
    name = models.CharField(max_length=25)
    user_name = models.CharField(max_length=20)
    mobile = models.CharField(max_length=15,default="0")
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    img=models.ImageField(default='1.jpg',blank=True)

    def __str__(self):
        return self.user_name # change object name in admin table

    class Meta:
        ordering= ['id'] #to Sort the values

class Customers(models.Model):
    name = models.CharField(max_length=50)
    mobile = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    id_type = models.CharField(max_length=50)
    id_number = models.CharField(max_length=50)
    address=models.CharField(max_length=50)
    notes=models.CharField(max_length=100)
    img=models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.name # change object name in admin table

    class Meta:
        ordering= ['id'] #to Sort the values

users/forms.py
from django import forms
from . import models
from django.forms import ModelForm,widgets
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

# class Login_form(forms.ModelForm):
#     class Meta:
#         model = User # table
#         fields = ['username','password']   # OR fields = ['id','name',....]
#         widgets ={
#             'username':forms.TextInput(attrs={'class':'form-control'}),
#             'password':forms.PasswordInput(attrs={'class':'form-control'})
#         }
#         labels = {
#             'username': '',
#             'password': '',
#         }

class users_form(forms.ModelForm):
    class Meta:
        model= models.Users
        fields = '__all__'

class Test_form(forms.ModelForm):
    class Meta:
        model = models.Test_model # table
        fields = '__all__'   # OR fields = ['id','name',....]

users/views.py
from django.shortcuts import render,redirect
from . import models,forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required

@login_required(login_url="/users/login")
def index(request):
	form= forms.users_form
	# user_name= request.POST.get('user_name')
	# user_email= request.POST.get('email')
	# data =Users(name=user_name,email=user_email)
	# data.save()
	message = 'from view'
	
	return render(request,"users/index.html",{'message2':message,'u_id':-1,'form':form ,'users':models.Users.objects.all().order_by('id')})

@login_required(login_url="/users/login")
def add(request):
	form = forms.users_form()
	if request.method == "POST":
		form = forms.users_form(request.POST)
		if form.is_valid():
			form.save()
			return redirect('users:index')
	return render(request,'users/add.html',{'form': form})


def delete(request,row_id):
	print(row_id)
	if row_id is not None :
		models.Users.objects.get(id=row_id).delete()
	return redirect('users:index')

def update_user(request,row_id):
	if row_id is not None :
		models.Users.objects.get(id=row_id).delete()
	return redirect('users:index')


def login_view(request):
	if request.method == "POST":
		form =AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request,user)
			if 'next' in request.POST: # if the login will redirect to a page
				return redirect(request.POST.get('next'))
			else:
				return redirect('users:index')
	else:
		form = AuthenticationForm()
	return render(request,'login.html',{'form': form})

# def login_view(request):
# 	if request.method == "POST":
# 		form =forms.Login_form(data=request.POST)
		
# 		username = request.POST['username']
# 		password = request.POST['password']
# 		user = authenticate(request, username=username, password=password)

# 		if user is not None:
# 			login(request,user)
# 			if 'next' in request.POST: # if the login will redirect to a page
# 				return redirect(request.POST.get('next'))
# 			else:
# 				return redirect('users:index')
# 		else:
# 			print('error login')
# 	else:
# 		form = forms.Login_form()
# 	return render(request,'login.html',{'form': form})

def logout_view(request):
	if request.method == "POST":
		logout(request)
		return redirect('users:login')
	else:
		form = AuthenticationForm()
	return render(request,'login.html',{'form': form})

@login_required(login_url="/users/login")
def about(request):
	return render(request,"about.html",{'user_name':request.user})


def signup(request):
	form = UserCreationForm()
	return render(request,'test.html',{'form' : form})

templates/users/add.html
{% extends 'base.html' %}

{% block content %}

<form class="site-form" method="post" action="{% url 'users:add' %}">
    <h1 class="h3 mb-3 fw-normal">Add User</h1>

    {% csrf_token %}

    {% comment %} to save the after login distenation {% endcomment %}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}"
    {% endif %}
    <input type="submit" value="save">
    <input type="button" onclick="location.href={% url 'users:index' %};" value="cancel">
    {{form}}
</form>



{% endblock content %}

templates/users/index.html
{% extends 'base.html' %}

{% block content %}

<!-- Table Card -->
<div class="col-xl-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Users Table</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions:</div>
                    <a class="dropdown-item" href="{% url 'users:add' %}"><i class="bi bi-file-earmark-plus"></i> New</a>
                    <div class="dropdown-divider"></div>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <form class="site-form-table" method="post" action="{% url 'users:index' %}">
                {% csrf_token %}
                <table id="table" class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">name</th>
                            <th scope="col">email</th>
                            <th scope="col">image</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for u in users %}
                        <tr>
                            <th scope="row" id="id">{{u.id}}</th>
                            <td >{{u.name}}</td>
                            <td>{{u.email}}</td>
                            <td><img src="{{ u.img.url }}" width="50" height="30"></td>
                            <td>
                                <a href="{% url 'users:delete' u.id %}" title="delete" class="btn btn-danger btn-circle btn-sm">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <!-- to get id of selected record -->
                <input hidden type="text" id="row_id">
            </form>
        </div>
    </div>
</div>


<!-- Data Card -->
<div class="col-xl-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Users Data</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions:</div>
                    <a class="dropdown-item" href="{% url 'users:update_user' u_id %}"><i class="bi bi-pencil-square"></i> Edit</a>
                    <div class="dropdown-divider"></div>

                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            
            {% verbatim %}

            <div id="app">
                {{ message }}
                <button @click="sayok2">ok</button>

            </div>
            {% endverbatim %}
            <form class="site-form" method="post" action="{% url 'users:index' %}">
                {% csrf_token %}

                {{form}}

                <a href="{% url 'users:update_user' u_id %}">edit</a>
            </form>

        </div>
    </div>
</div>



{% endblock content %}

{% block scripts %}
<script>
    
    const { createApp } = Vue
    createApp({
      data() {
        return {
          message: 'Hello Vue2'
        }
      },
      methods: {
        sayok: function(){
            this.message= 'Date()'
        },
        sayok2: function(){
            this.message= Date()
        },
      }
    }).mount('#app')
  </script>

  <script>
    //to change the selected row color and send the id to text input
    $("#table tr").click(function(){
        $(this).addClass('selected').siblings().removeClass('selected');    
        //var id=$(this).find('th:first').html();
        var id=$(this).find('th:first').html();
        document.getElementById("row_id").value=id;

        //alert(id)
    });
</script>
{% endblock %}